export class RequestDetails {
    ClientTypeName: string;
    OrganizationTypeName: string;
    ClientName: string;
    Designation: string;
    PhoneNo1: string;
    PhoneNo2: string;
    Email: string;
    PANNO: string;
    RequestId: number;
    RequestTypeId: number | null;
    RequestNo: string;
    RequestDate: string | null;
    AdvisorId: number | null;
    RequestServiceId: number;
    SourceId: number | null;
    ClientBehaviourId: number | null;
    ServiceName: string;
    FinancialYear: string;
    DiscountType: string;
    LeadSourceName: string;
    LeadStatusName: string;
    StageName: string;
    AdvisorName: string;
    AssignedOn: string | null;
    LastFollowupDate: string | null;
    NextFollowupDate: string | null;
    ClientBehaviourName: string;
    DepartmentName: string;
    ServiceQuotedPrice : number;
    ServiceQuotedDiscountPercent: number | null;
    ServiceQuotedDicountAmount: number | null;
    ServiceQuotedNetAmount: number | null;
    ServiceAgreedDiscountPercent: number | null;
    ServiceAgreedDiscountAmount: number | null;
    ServiceAgreedNetAmount: number | null;

    ServiceTotalQuotedPrice : number;
    ServiceTotalQuotedDiscountPercent: number | null;
    ServiceTotalQuotedDicountAmount: number | null;
    ServiceTotalQuotedNetAmount: number | null;
    ServiceTotalAgreedDiscountPercent: number | null;
    ServiceTotalAgreedDiscountAmount: number | null;
    ServiceTotalAgreedNetAmount: number | null;

    TotalQuotedAmount: number | null;
    TotalQuotedDiscountAmount: number | null;
    TotalQuotedNetAmount: number | null;
    TotalAgreedDiscountAmount: number | null;
    TotalAgreedNetAmount: number | null;
    RevenueAmount: number | null;
    ServiceId: number | null;
    DepartmentId: number | null;
    LeadStatusId: number | null;
    Remark: string;
    StageId: number | null;
    TermsAndConditions: string;
    ClientTypeId: number | null;
    ServiceDiscountType: number | null;
    IsSent:boolean;
    SentOn:Date;
    SentBy:number;
    AddedBy: number | null;
    AddedOn: string | null;
    UpdatedBy: number | null;
    UpdatedOn: string | null;
  TransferPendingFollowUp: boolean;
}