export class ClientMaster {
    ClientId: number | null;
    OrganizationId: number | null;
    ClientName: string;
    ClientTypeName : string;
    ClientTypeId : number;
    
    ContactPersonId: number;
    Salutation: string;
  
    LastName: string;
    FirstName: string;
    MiddleName: string;
    Designation: string;
    PhoneNo1: string;
    PhoneNo2: string;
    GenderId: number | null;
    Email: string;
    DOB: string | null;
    PANNO: string;
    AadharNo: string;
    ContactPersonAddress: string;
    ContactPersonDistrict: string;
    ContactPersonState: string;
    ContactPersonCountry: string;
    IsActive: boolean | null;
    OrganizationTypeId: number | null;
    OrganizationName: string;
    OrganizationCode: string;
    Description: string;
    TariffId: number | null;
    Website: string;
    OrganizationEmail: string;
    OrganizationMobileNo: string;
    OrganizationPhoneNo: string;
    OrganizationAddress: string;
    OrganizationDistrict: string;
    OrganizationState: string;
    OrganizationCountry: string;
    OrganizationPinCode: string;
    IndustryType: string;
    TotalEmployees: number | null;
    OrganizationPANNO: string;
    GSTNO: string;
    IsDND: boolean | null;
    ClientSourceId: number | null;
    AdvisorId: number | null;
    AddedDate: string | null;
    IsAssigned: boolean;
    DepartmentName: string | null;
    Amount: number;
    AdvisorName: string | null;
}