export class ClientMaster {
    ClientId: number;
    GenderId: number | null;
    ClientName: string;
    CorporateName :string;
    OrganizationId: number | null;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    DoB: Date;
    FatherFirstName: string;
    FMiddleName: string;
    FLastName: string;
    Email: string;
    Address: string;
    PinCode: string;
    Remark: string;
    MobileNo: string;
    AlternateMobileNo: string;
    ContactPerson: string;
    LandLine: string;
    GSTNO: string;
    AdharNo: string;
    LoginName: string;
    PANNo: string;
    HNo: string;
    Street: string;
    Area: string;
    Taluka: string;
    District: string;
    State: string;
    OfficeAddress: string;
    OfficeHNo: string;
    OfficeStreet: string;
    OfficeArea: string;
    OfficeTaluka: string;
    OfficeDistrict: string;
    OfficeState: string;
    OfficePinCode: string;
    Password: string;
    ProfilePhoto: string;
    AddedBy: number | null;
    AddedDate: Date | null;
    UpdatedBy: number | null;
    UpdatedDate: Date | null;
    IsAssigned : boolean;
    DepartmentName : string;
    Amount : number;
    AdvisorId : number;
    AdvisorName:string;
}